FROM openjdk:13-jdk-alpine
COPY target/KomunalnaPolicijaIInspekcija-0.0.1-SNAPSHOT.jar KomunalnaPolicijaIInspekcija-0.0.1-SNAPSHOT.jar
EXPOSE 9002
ENTRYPOINT ["java","-jar","KomunalnaPolicijaIInspekcija-0.0.1-SNAPSHOT.jar"]