version: '3.1'

networks:
  maticar:
    name: maticar

services:
  maticar-frontend:
    build:
      context: ./frontend/
    container_name: maticar-frontend
    networks:
      maticar:
        aliases:
          - frontend
    ports:
      - "4001:4001"

  maticar:
    build:
      context: ./maticar-backend/
      args:
        - APP_VERSION
    container_name: maticar
    volumes:
      - ./maticar-backend/htmlcov:/opt/app/htmlcov
    environment:
      - DEVELOP
      - APP_VERSION
      - LOG_LEVEL
      - SECRET
      - ALGORITHM
      - MYSQL_USER
      - AUTH_SERVER_API
      - MYSQL_PASSWORD
      - MYSQL_DB
      - MYSQL_HOST
      - MYSQL_PORT
      - REDIS_HOST
    networks:
      maticar:
        aliases:
          - app
    ports:
      - "4002:4002"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      maticar:
        aliases:
        - ${MYSQL_HOST}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  mysql:
    driver: local
  redis:
    driver: local
