###
GET http://localhost:4567/example
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluaXN0cmF0b3IiLCJzdWIiOiI2MjM2Nzc2NzJiYmQ5Mzc3Yzk2Nzg1NTkiLCJyb2xlcyI6WyJhZG1pbiIsIm1hdGljYXJfYWRtaW5pc3RyYXRvciJdLCJpZGVudGl0eU51bWJlciI6IjEyMzQ1Njc4IiwiaWF0IjoxNjUxMTgyNjI5LCJleHAiOjE2NTExODk4Mjl9.-s94dBdK-JHQtaSqGB16WkBbo3j-kloAP7B7gzLj7mA
Content-Type: application/json
