version: '3.7'

services:
  mup-vozila-backend:
    build: 
      context: ./mup-vozila
      dockerfile: Dockerfile
    ports:
      - "6001:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mup-vozila?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: newuser
      SPRING_DATASOURCE_PASSWORD: NewUser123
    networks:
      - backend
      - frontend  

  db:
    image: mysql:8.0-oracle
    ports:
      - "6002:3306"
    restart: always
    environment:
      MYSQL_DATABASE: mup-vozila
      MYSQL_USER: newuser
      MYSQL_PASSWORD: NewUser123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  mup-vozila-frontend:
    build:
      context: ./mup-vozila-frontend
      dockerfile: Dockerfile
    ports:
      - "6003:80"
    restart: always
    networks:
      - frontend  

volumes:
  db-data:

networks:
  backend:
  frontend:
  


    