version: '3.7'

services:
  edfeahs-backend:
    build:
      context: ./edfeahs
      dockerfile: Dockerfile
    ports:
      - "7001:8080"
    restart: always
    container_name: edfeahs-backend
    depends_on:
      - edfeahs-mysql
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mup-vozila?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DATABASE=edfeahs
    networks:
      - backend

  edfeahs-mysql:
    image: mysql:8.0.29
    ports:
      - "7002:3306"
    restart: always
    container_name: edfeahs-mysql
    volumes:
      - edfeahs-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: edfeahs
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

volumes:
  edfeahs-mysql:
    driver: local

networks:
  backend:

